### ISSUE TITLE
Dynamic exception specifications are deprecated in C++11

### ISSUE THREAD

**Issue by jelkose** [dspeterson/dory#13]
When trying to build on Ubuntu 18.04.1 LTS with all dependencies installed I get the following message:
```
src/base/event_semaphore.cc:93:44: error: dynamic exception specifications are deprecated in C++11 [-Werror=deprecated]
 void TEventSemaphore::Push(uint64_t count) throw(std::system_error) {
                                            ^~~~~
cc1plus: all warnings being treated as errors
scons: *** [out/release/base/event_semaphore.o] Error 1
```
That does not seem to be dramatic, but as the routine is told to stop if there is any warning the build does not complete.
Do I have to change the configuration or is there any other way to build dory with a compiler using C++ >= V11 ?
I got the version 7.3.0 of the gcc compiler installed on my system.

Regards,
Jelko

**Comment by dspeterson** [comment]
Thanks for catching this.  I didn't even know there were any exception specifications in the code.  A lot of the stuff in the base directory is stuff I inherited from the company where I worked when I wrote dory.  I just created a new release with all exception specifications removed.  Let  me know if you run into any more problems.

**Comment by jelkose** [comment]
Thanks for helping!
Sadly I have to say that there is still a warning/error when trying to build:
```
src/base/event_semaphore_notifier.cc:26:1: error: mangled name for 'Base::TEventSemaphoreNotifier::TEventSemaphoreNotifier(Base::TEventSemaphore&, const TErrorHandler&)' will change in C++17 because the exception specification is part of a function type [-Werror=noexcept-type]
 TEventSemaphoreNotifier::TEventSemaphoreNotifier(TEventSemaphore &sem,
 ^~~~~~~~~~~~~~~~~~~~~~~
```
Now it's about C++17 ..
Regards,
Jelko

**Comment by dspeterson** [comment]
I'll try building with gcc 7.3.0 this weekend and fix any remaining build errors.  This particular warning is harmless, so in the meantime you can quiet it by adding `'-Wno-noexcept-type'` to the `CCFLAGS` list starting on line line 146 of the `SConstruct` file in the root of the repo.  If you want to go ahead and fix it before I get to it this weekend, feel free to submit a pull request.  Thanks!

**Comment by jelkose** [comment]
Alright I added it and now it works. 
I think by fixing the last few issues it should work with gcc 7.3.0.
Thanks a lot for helping!

**Comment by dspeterson** [comment]
fixed in version 2.1.3
