### ISSUE TITLE
gzip: error: this statement may fall through

### ISSUE THREAD

**Issue by jelkose** [dspeterson/dory#15]
When trying to build on Ubuntu 18.04 with gcc 7.3.0, I'm getting the following error:

```
src/dory/compress/gzip/gzip_codec.cc: In function 'int CheckStatus(int, const z_stream&, const char*)':
src/dory/compress/gzip/gzip_codec.cc:82:21: error: this statement may fall through [-Werror=implicit-fallthrough=]
       ThrowZlibError(strm, zlib_function_name, "Z_STREAM_ERROR");
       ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/dory/compress/gzip/gzip_codec.cc:85:5: note: here
     case Z_VERSION_ERROR: {
     ^~~~
```
It occors at several places in the gzip code.
To get dory building anyway, `-Wno-implicit-fallthrough` can be added to the CXX compiler flags.

**Comment by dspeterson** [comment]
Hmm...  Ok, I'll create a fix this weekend.  I'll probably just add a break at the end of each case to keep the compiler happy even though it's not really necessary here.  It's good to see that gcc added a warning for this, since omitting a break in a switch statement is often a bug.

**Comment by jelkose** [comment]
Ok, thanks. 
Until then, it compiles and runs fine by adding the flag. :)

**Comment by dspeterson** [comment]
fixed in version 2.1.3
